/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wallet_package;

import com.placeholder.PlaceHolder;
import java.awt.Font;
import java.awt.event.KeyEvent;
import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author i quit techno
 */
public class Create_account extends javax.swing.JFrame {

    /**
     * Creates new form Create_account
     */
    private int u,p;
    public Create_account() {
        initComponents();
        format();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void format(){
        //username.setToolTipText("Username");
        PlaceHolder x ;
       // x.setColorHolder(Color.orange);font	Arial Rounded MT Bold 18 Plain
       x = new PlaceHolder(username,"Username");
       x = new PlaceHolder(password,"Password");
      //  x = new PlaceHolder()
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        password = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Wallet - SignUp");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(960, 530));
        jPanel1.setLayout(null);

        password.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });
        jPanel1.add(password);
        password.setBounds(70, 240, 340, 40);

        username.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        username.setToolTipText("");
        username.setName(""); // NOI18N
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });
        jPanel1.add(username);
        username.setBounds(70, 180, 340, 40);

        jButton1.setBackground(new java.awt.Color(51, 0, 255));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SIGN UP");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 204), 2, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(270, 310, 140, 40);

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(440, 190, 130, 20);

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(440, 250, 140, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wallet_package/signup.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(390, 0, 570, 540);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel5.setText("Create your Account.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 120, 340, 40);

        jButton2.setBackground(new java.awt.Color(51, 0, 255));
        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("EXIT");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 204), 2, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(70, 310, 140, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
       // password.setText("");
       p =0;
        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true));
        jLabel3.setText("");
        Font font= new Font("Arial Rounded MT",Font.BOLD,18);
        password.setFont(font);
    }//GEN-LAST:event_passwordFocusGained

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if("Enter Username !!".equals(jLabel2.getText()) || "Enter Password !!".equals(jLabel3.getText())){
                    username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
                    jLabel2.setText("Enter Username !!");
               
                    password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
                    jLabel3.setText("Enter Password !!");
               
                
            }else{
            
            try {
                try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Wallet_Database", "wallet", "12345")) {
                    Statement st = con.createStatement();
                    //ResultSet rs = st.executeQuery("SELECT * FROM LOGIN_DATA");
                    int x = st.executeUpdate("INSERT INTO LOGIN_DATA VALUES('"+username.getText()+"','"+password.getText()+"')");
                }
                //JOptionPane.showMessageDialog(null,"Welcome to Wallet. Click OK to login.","Welcome",JOptionPane.INFORMATION_MESSAGE);
                int ok =JOptionPane.showConfirmDialog(null,"Welcome to Wallet. Click OK to login.","Welcome",JOptionPane.OK_OPTION);
                //JOptionPane.OK_OPTION 
                if(ok == 0 ){
                    this.dispose();
                     new LoginScreen().show();
                
                }else if(ok == 1)
                {
                    username.setText("");
                    password.setText("");
                    format();
                }
                
               
                //JOptionPane.showConfirmDialog(rootPane, username, title, WIDTH, HEIGHT, icon)
                
            
   
            } catch (SQLException ex) {
                Logger.getLogger(Create_account.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
        }
    }//GEN-LAST:event_passwordKeyPressed

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        // TODO add your handling code here:
        
        u = 0;
        username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true));
        jLabel2.setText("");
        Font font= new Font("Arial Rounded MT",Font.BOLD,18);
        username.setFont(font);
    }//GEN-LAST:event_usernameFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
            if("Enter Username !!".equals(jLabel2.getText()) || "Enter Password !!".equals(jLabel3.getText())){
                    username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
                    jLabel2.setText("Enter Username !!");
               
                    password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
                    jLabel3.setText("Enter Password !!");
               
                
            }else{
            
            try {
                try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Wallet_Database", "wallet", "12345")) {
                    Statement st = con.createStatement();
                    //ResultSet rs = st.executeQuery("SELECT * FROM LOGIN_DATA");
                    int x = st.executeUpdate("INSERT INTO LOGIN_DATA VALUES('"+username.getText()+"','"+password.getText()+"')");
                }
                int ok =JOptionPane.showConfirmDialog(null,"Welcome to Wallet. Click OK to login.","Welcome",JOptionPane.OK_OPTION);
                //JOptionPane.OK_OPTION 
                if(ok == 0 ){
                    this.dispose();
                     new LoginScreen().show();
                
                }else if(ok == 1)
                {
                    username.setText("");
                    password.setText("");
                    format();
                }
            
   
            } catch (SQLException ex) {
                Logger.getLogger(Create_account.class.getName()).log(Level.SEVERE, null, ex);
            }
            

        }
       

                   
         

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if("Enter Username !!".equals(jLabel2.getText()) || "Enter Password !!".equals(jLabel3.getText())){
                    username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
                    jLabel2.setText("Enter Username !!");
               
                    password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
                    jLabel3.setText("Enter Password !!");
               
                
            }else{
            
            try {
                try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Wallet_Database", "wallet", "12345")) {
                    Statement st = con.createStatement();
                    //ResultSet rs = st.executeQuery("SELECT * FROM LOGIN_DATA");
                    int x = st.executeUpdate("INSERT INTO LOGIN_DATA VALUES('"+username.getText()+"','"+password.getText()+"')");
                }
                int ok =JOptionPane.showConfirmDialog(null,"Welcome to Wallet. Click OK to login.","Welcome",JOptionPane.OK_OPTION);
                //JOptionPane.OK_OPTION 
                if(ok == 0 ){
                    this.dispose();
                     new LoginScreen().show();
                }else if(ok == 1)
                {
                    username.setText("");
                    password.setText("");
                    format();
                }
            
   
            } catch (SQLException ex) {
                Logger.getLogger(Create_account.class.getName()).log(Level.SEVERE, null, ex);
            }
            }

        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        // TODO add your handling code here:
        if(u == 1){
                    
                   username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true));
                   jLabel2.setText("");
        }
        else{ //if("Enter Username !!".equals(jLabel2.getText()) || "Enter Password !!".equals(jLabel3.getText())){
        
        username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
                    jLabel2.setText("Enter Username !!");
        }
        u =0;
    }//GEN-LAST:event_usernameFocusLost

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        // TODO add your handling code here:
        if(p == 1){
                    
                  password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true));
                    jLabel3.setText("");
        }
        else{ //if("Enter Username !!".equals(jLabel2.getText()) || "Enter Password !!".equals(jLabel3.getText())){
        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
                    jLabel3.setText("Enter Password !!");
        
        }
        p =0;
        
    }//GEN-LAST:event_passwordFocusLost

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped
        // TODO add your handling code here:
        u =1;
    }//GEN-LAST:event_usernameKeyTyped

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
        // TODO add your handling code here:
        p = 1;
    }//GEN-LAST:event_passwordKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginScreen().show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPasswordField password;
    public javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
