/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wallet_package;

import com.placeholder.PlaceHolder;
import com.sun.glass.events.KeyEvent;
import java.awt.Font;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author i quit techno
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
     private int u,p;
    public LoginScreen() {
        initComponents();
        format();
    }
    private void format(){
        username.setForeground(new java.awt.Color(0, 0, 255));
        password.setForeground(new java.awt.Color(0, 0, 255));
        //username.setToolTipText("Username");
        PlaceHolder x ;
       // x.setColorHolder(Color.orange);font	Arial Rounded MT Bold 18 Plain
        x = new PlaceHolder(username,"Username");
        x = new PlaceHolder(password,"Password");
    }
    
    
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        password = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - Wallet");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(960, 530));
        jPanel1.setLayout(null);

        password.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(0, 51, 255));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });
        jPanel1.add(password);
        password.setBounds(70, 240, 340, 40);

        username.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(0, 0, 255));
        username.setToolTipText("");
        username.setName(""); // NOI18N
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });
        jPanel1.add(username);
        username.setBounds(70, 180, 340, 40);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(430, 250, 120, 20);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(430, 190, 120, 20);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel6.setText("Forgot password?");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 290, 160, 20);

        jButton1.setBackground(new java.awt.Color(51, 0, 255));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 204), 2, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(270, 330, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wallet_package/login11.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(390, 0, 570, 540);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel5.setText("Login");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 100, 160, 40);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Create your account.");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 140, 140, 20);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setText("Don't have an account?");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 140, 140, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int flag =0;
        try {
            try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Wallet_Database", "wallet", "12345")) {
                Statement st = con.createStatement();
                try (ResultSet rs = st.executeQuery("SELECT * FROM LOGIN_DATA")) {
                    while(rs.next())
                    {
                        
                        if ((username.getText() == null ? rs.getString(1) == null : username.getText().equals(rs.getString(1))) && (password.getText() == null ? rs.getString(2) == null : password.getText().equals(rs.getString(2)))) {
                            flag = 1;                            
                        }
                    }
                    if(flag == 1)
                    {
                        this.hide();
                        //this.dispose();
                         new HomePage().setVisible(true);
                       // us1.setText("Welcome Back");
                    }
                    else if (flag == 0 ) {
                          JOptionPane.showMessageDialog(null,"Username or Password is wrong !!","Error",JOptionPane.INFORMATION_MESSAGE);
                         username.setText("");
                         password.setText("");
                         
                            format();
                        
                        
                 //       infoBox("Welcome to Wallet you are registered. Login NOW !!","Registered");
                      
                 //       int x = st.executeUpdate("INSERT INTO LOGIN_DATA VALUES('"+username.getText()+"','"+password.getText()+"')");
                    }
                }
            }    
        } catch (SQLException ex) {
            Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
        }           
                        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            int flag =0;
        try {
            try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Wallet_Database", "wallet", "12345")) {
                Statement st = con.createStatement();
                try (ResultSet rs = st.executeQuery("SELECT * FROM LOGIN_DATA")) {
                    while(rs.next())
                    {
                        
                        if ((username.getText() == null ? rs.getString(1) == null : username.getText().equals(rs.getString(1))) && (password.getText() == null ? rs.getString(2) == null : password.getText().equals(rs.getString(2)))) {
                            flag = 1;                            
                        }
                    }
                    if(flag == 1)
                    {
                        this.hide();
                        //this.dispose();
                         new HomePage().setVisible(true);
                       // us1.setText("Welcome Back");
                    }
                    else if (flag == 0 ) {
                        JOptionPane.showMessageDialog(null,"Username or Password is wrong !!","Error",JOptionPane.INFORMATION_MESSAGE);
                        //JOptionPane.showMessageDialog(null,"Username or Password is wrong !!","Error", HEIGHT);
                        username.setText("");
                         password.setText("");
                            format();
                    }
                }
            }    
        } catch (SQLException ex) {
            Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
        }           
                        
            
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            //if(username == ""){
                
           // }
            int flag =0;
        try {
            try (Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Wallet_Database", "wallet", "12345")) {
                Statement st = con.createStatement();
                try (ResultSet rs = st.executeQuery("SELECT * FROM LOGIN_DATA")) {
                    while(rs.next())
                    {
                        
                        if ((username.getText() == null ? rs.getString(1) == null : username.getText().equals(rs.getString(1))) && (password.getText() == null ? rs.getString(2) == null : password.getText().equals(rs.getString(2)))) {
                            flag = 1;                            
                        }
                    }
                    if(flag == 1)
                    {
                         this.hide();
                         //this.dispose();
                         new HomePage().setVisible(true);
                       // us1.setText("Welcome Back");
                    }
                    else if (flag == 0 ) {
                         JOptionPane.showMessageDialog(null,"Username or Password is wrong !!","Error",JOptionPane.INFORMATION_MESSAGE);
                        username.setText("");
                         password.setText("");
                         //username.requestFocusInWindow();
                            format();
                    }
                }
            }    
        } catch (SQLException ex) {
            Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
        }           
        }
        
    }//GEN-LAST:event_passwordKeyPressed

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        // TODO add your handling code here:
        u = 0;
        jLabel2.setText("");
        username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true));
        Font font= new Font("Arial Rounded MT",Font.BOLD,18);
        username.setForeground(new java.awt.Color(0, 0, 255));
        username.setFont(font);
    }//GEN-LAST:event_usernameFocusGained

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
         p =0;
        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true));
        jLabel7.setText("");
        Font font= new Font("Arial Rounded MT",Font.BOLD,18);
        password.setFont(font);
        
    }//GEN-LAST:event_passwordFocusGained

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.hide();
        new Create_account().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        // TODO add your handling code here:
        if(u == 1){
                    
                   username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true));
                   jLabel2.setText("");
        }
        else{ //if("Enter Username !!".equals(jLabel2.getText()) || "Enter Password !!".equals(jLabel3.getText())){
        
        username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
                    jLabel2.setText("Enter Username !!");
        }
        u =0;
    }//GEN-LAST:event_usernameFocusLost

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        // TODO add your handling code here:
         if(p == 1){
                    
                  password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true));
                    jLabel7.setText("");
        }
        else{ //if("Enter Username !!".equals(jLabel2.getText()) || "Enter Password !!".equals(jLabel3.getText())){
        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
                    jLabel7.setText("Enter Password !!");
        
        }
        p =0;
    }//GEN-LAST:event_passwordFocusLost

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped
        // TODO add your handling code here:
        u = 1;
    }//GEN-LAST:event_usernameKeyTyped

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
        // TODO add your handling code here:
        p =1;
    }//GEN-LAST:event_passwordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPasswordField password;
    public javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
